version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"  # Expose for development
      - "8081:8081"  # Expose for production server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

