name: CI Pipeline

on:
  push:
    branches:
      - main
      - github-actions
      - githubactions-again
  pull_request:
    branches:
      - main
      - github-actions
      - githubactions-again

jobs:
  # Backend job
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Maven Tests
        working-directory: ./ # Adjust to the backend root directory
        run: mvn clean test

  # Frontend job
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: ./ActionProeve # Adjust to the frontend root directory
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./ActionProeve # Adjust to the frontend root directory
        run: npm run test:unit
